version: '3'
services:
  spark-master:
    image: bde2020/spark-master:2.3.2-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
      - "18080:18080"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    network_mode: "bridge"
    # volumes:
    #   - /home/lucian/workspace/ANPIS/engine/target:/jars
  spark-worker-1:
    image: bde2020/spark-worker:2.3.2-hadoop2.7
    container_name: spark-worker-1
    links :
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    network_mode: "bridge"
    # volumes:
    #   - /home/lucian/workspace/ANPIS/engine/target:/jars